#!/usr/bin/env python3
"""Compile the reviewed spending priorities used by the player-flow tests."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=ROOT / "build/orders_generated.h")
    args = parser.parse_args()
    content = json.loads((ROOT / "content/campaigns.json").read_text())
    orders = json.loads((ROOT / "content/build_orders.json").read_text())
    out = ["/* Generated by compile_build_orders.py; do not edit. */"]
    for level in content["maps"]:
        symbol = level["id"].replace("-", "_")
        for campaign in content["campaigns"]:
            fixtures = {f["id"]: i for i, f in enumerate(campaign["fixtures"])}
            out.append(f'static const pt_sim_order_entry {symbol}_{campaign["id"]}_orders[] = {{')
            previous = 0
            for item in orders["maps"][level["id"]][campaign["id"]]["optimal"]:
                assert item.get("action", "build") in ("build", "repair"), "unknown order action"
                wave, pad = item["wave"], item["pad"]
                tier = 255 if item.get("action") == "repair" else item["tier"]
                assert previous <= wave <= len(campaign["waves"]), "orders must follow wave order"
                assert 1 <= pad <= len(level["pads"]) and (0 <= tier < 3 or tier == 255)
                previous = wave
                kind = fixtures[item["fixture"]]
                out.append(f"    {{{wave}u, {pad}u, {kind}u, {tier}u}},")
            out.append("};")
    args.out.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
