#!/usr/bin/env python3
"""Compile the verified sound manifest into bounded Kilix cue tables.

Stable game IDs are sparse and exceed the mixer's 64 slots. Keep them intact
and assign a separate dense bank index to each logical cue (including music).
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def compile_manifest() -> str:
    manifest = json.loads((ROOT / "assets/audio/manifest.json").read_text())
    ids = json.loads((ROOT / "content/stable_ids.json").read_text())
    cues = manifest["cues"]
    names = sorted(cues)
    if len(names) > 64:
        raise ValueError("cue bank exceeds 64 slots")
    out = ["/* Generated by compile_audio_runtime.py; do not edit. */",
           f"#define PT_AUDIO_BANK_COUNT {len(names)}u",
           "static const kilix_game_audio_cue_spec cue_specs[] = {"]
    for slot, name in enumerate(names):
        cue = cues[name]
        if len(cue["files"]) > 8:
            raise ValueError(f"too many variations for {name}")
        if not name.startswith("music.") and cue["stable_id"] != ids["cues"][name]:
            raise ValueError(f"stable cue ID mismatch: {name}")
        for variant, file in enumerate(cue["files"]):
            out.append(f'    {{{slot}u, {variant}u, "audio/{file}", '
                       f'{float(cue["gain"]):.6f}f, 1.0f, true}},')
    out += ["};", "static const kilix_game_music_scene_spec scene_specs[] = {"]
    for name, scene in ids["scenes"].items():
        cue_name = f"music.{name}"
        cue = cues[cue_name]
        out.append(f'    {{{scene}u, {names.index(cue_name)}u, 0u, 1.0f, '
                   f'{str(cue["loop"]).lower()}}},')
    out += ["};", "static const pt_audio_metadata cue_metadata[] = {"]
    for slot, name in enumerate(names):
        if name.startswith("music."):
            continue
        cue = cues[name]
        bus = str(cue["bus"]).upper()
        out.append(f'    {{{ids["cues"][name]}u, {slot}u, '
                   f'KILIX_GAME_AUDIO_BUS_{bus}, '
                   f'{float(cue["cooldown_ms"]) / 1000:.6f}f}},')
    out += ["};", ""]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=ROOT / "build/audio_generated.h")
    args = parser.parse_args()
    result = compile_manifest()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(result)
    print("audio runtime OK")


if __name__ == "__main__":
    main()
